// Cultivated apple (Malus domestica) — a free-standing standard orchard tree.
// One persistent leader carries widely angled, vertically separated scaffold
// sets; progressively shorter laterals end in dense spur-scale fruiting wood.

import { broadleafControls } from './broadleaf-controls.js';

export const apple = {
  name: 'Cultivated Apple',
  latin: 'Malus domestica',
  bark: 'apple_bark_albedo.png',
  leaf: 'apple_single_albedo.png',
  biome: 'temperate',
  controls: broadleafControls,
  foliage: {
    mode: 'leaves',
    clustersPerBranch: 4,
    clusterSize: 0.66,
    clusterSizeVar: 0.18,
    clusterQuads: 2,
    tint: 0xc8dda5,
    leavesPerBranch: 9,
    cardCoverage: 1.5,
    cardRadialPlanes: 2,
    cardCrownUnderlay: true,
    cardCrownUnderlayLateralScale: 1.35,
    mobileNearTwigCollapse: true,
    size: 0.22,
    downAngle: 54,
    bend: 0,
    trunkClearRadius: 0.25,
  },
  params: {
    scale: 4.6,
    scaleV: 0.34,
    levels: 4,
    ratio: 0.052,
    ratioPower: 1.22,
    baseSize: 0.25,
    shape: 0,
    flare: 0.68,
    attractionUp: 0.28,
    attractionUpMinLevel: 1,
    baseSplits: 0,
    baseSplitAngle: 0,
    //          trunk L1 scaffold  L2 lateral  L3 fruiting spur
    length:    [1,    0.55,        0.36,       0.22],
    lengthV:   [0,    0.1,         0.12,       0.15],
    taper:     [1,    1,    1,    1],
    curveRes:  [9,    6,    4,    3],
    curve:     [5,    20,   24,   10],
    curveBack: [0,   -16,  -12,    0],
    curveV:    [8,    22,   38,   44],
    downAngle: [0,    58,   48,   44],
    downAngleV:[0,    10,   18,   22],
    rotate:    [0,    137,  137,  137],
    rotateV:   [0,    18,   28,   32],
    branches:  [0,    12,   10,    7],
    branchTiers:      [0, 3, 0, 0],
    branchTierSpread: [0, 0.62, 1, 1],
    radialSegments: [10, 7, 5, 4],
  },
};
