// Sweet cherry (Prunus avium) — a vigorous free-standing orchard form with a
// strong central leader. Tight ascending branches gather below annual leader
// extensions, leaving the characteristic gaps between successive branch tiers.

import { broadleafControls } from './broadleaf-controls.js';

export const cherry = {
  name: 'Sweet Cherry',
  latin: 'Prunus avium',
  bark: 'cherry_bark_albedo.png',
  leaf: 'cherry_single_albedo.png',
  biome: 'temperate',
  controls: broadleafControls,
  foliage: {
    mode: 'leaves',
    clustersPerBranch: 3,
    clusterSize: 0.64,
    clusterSizeVar: 0.2,
    clusterQuads: 2,
    tint: 0xcce0a9,
    leavesPerBranch: 10,
    cardCoverage: 1.5,
    cardRadialPlanes: 2,
    cardCrownUnderlay: true,
    cardCrownUnderlayLateralScale: 1.3,
    mobileNearTwigCollapse: true,
    size: 0.23,
    downAngle: 48,
    bend: 0,
    trunkClearRadius: 0.3,
  },
  params: {
    scale: 5.2,
    scaleV: 0.38,
    levels: 4,
    ratio: 0.041,
    ratioPower: 1.34,
    baseSize: 0.28,
    shape: 7,
    flare: 0.42,
    attractionUp: 0.38,
    attractionUpMinLevel: 1,
    baseSplits: 0,
    baseSplitAngle: 0,
    //          trunk L1 tier shoot  L2 lateral  L3 fruiting spur
    length:    [1,    0.52,           0.36,       0.23],
    lengthV:   [0,    0.08,           0.12,       0.14],
    taper:     [1,    1,    1,    1],
    curveRes:  [10,   6,    4,    3],
    curve:     [3,    12,   18,    8],
    curveBack: [0,    -6,  -10,    0],
    curveV:    [6,    18,   32,   38],
    downAngle: [0,    46,   46,   48],
    downAngleV:[0,    10,   16,   20],
    rotate:    [0,    137,  137,  137],
    rotateV:   [0,    13,   24,   28],
    branches:  [0,    16,    7,    5],
    branchTiers:      [0, 4, 0, 0],
    branchTierSpread: [0, 0.22, 1, 1],
    radialSegments: [9, 7, 5, 4],
  },
};
